// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp.Core.Data;

#nullable disable

namespace WpfApp.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250909095831_categoryTable-withName")]
    partial class categoryTablewithName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("WpfApp.Core.Models.AtomicHabitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHabitDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Streak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryModelId");

                    b.ToTable("AtomicHabits", (string)null);
                });

            modelBuilder.Entity("WpfApp.Core.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoryModel", (string)null);
                });

            modelBuilder.Entity("WpfApp.Core.Models.ProgressHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtomicHabitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HabitCheckDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHabitChecked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AtomicHabitId");

                    b.ToTable("ProgressHistory", (string)null);
                });

            modelBuilder.Entity("WpfApp.Core.Models.AtomicHabitModel", b =>
                {
                    b.HasOne("WpfApp.Core.Models.CategoryModel", "CategoryModel")
                        .WithMany("AtomicHabits")
                        .HasForeignKey("CategoryModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryModel");
                });

            modelBuilder.Entity("WpfApp.Core.Models.ProgressHistoryModel", b =>
                {
                    b.HasOne("WpfApp.Core.Models.AtomicHabitModel", "AtomicHabit")
                        .WithMany("ProgressHistories")
                        .HasForeignKey("AtomicHabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtomicHabit");
                });

            modelBuilder.Entity("WpfApp.Core.Models.AtomicHabitModel", b =>
                {
                    b.Navigation("ProgressHistories");
                });

            modelBuilder.Entity("WpfApp.Core.Models.CategoryModel", b =>
                {
                    b.Navigation("AtomicHabits");
                });
#pragma warning restore 612, 618
        }
    }
}
